#!/bin/sh

# run-qt5
# This file is part of the YATE Project http://YATE.null.ro
#
# Yet Another Telephony Engine - a fully featured software PBX and IVR
# Copyright (C) 2005-2020 Null Team
#
# This software is distributed under multiple licenses;
# see the COPYING file in the main directory for licensing
# information for this specific distribution.
#
# This use of this software may be subject to additional restrictions.
# See the LEGAL file in the main directory for details.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


# Script to run the Qt5 client from the build directory

if [ -x yate-qt5 -a -x ../run ]; then
    # Need to put the path to extra Qt/KDE libraries here
    # export LD_LIBRARY_PATH=
    cd ..; exec ./run --executable clients/yate-qt5 "$@"
else
    echo "Could not find client executable or run script" >&2
fi
